name: cyclop
description: a flutter colorpicker with an eyedropper
version: 0.2.0
author:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^2.1.13
  quiver: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/grid.png
