name: cyclop
description: Cyclop is a flutter color palette with an optional eyedropper tool on mobile and desktop.
version: 0.3.0+1
homepage: https://github.com/rxlabz/cyclop

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.1
  quiver: ^3.0.0
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/grid.png
