name: cyclop
description: An experimental flutter colorpicker with an optional eyedropper tool ( Material colors swatches, AHSL, ARGB and custom swatches library )
version: 0.5.0
homepage: https://github.com/rxlabz/cyclop

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.1
  quiver: ^3.0.0
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/grid.png
